export const DEMO_ACTION = "DEMO_ACTION"

export const REQUESTING_GET_REPOSITORIES = "REQUESTING_GET_REPOSITORIES"
export const GET_REPOSITORIES = "GET_REPOSITORIES"
export const ERROR_GET_REPOSITORIES = "ERROR_GET_REPOSITORIES"

export const STAR_REPOSITORY = "STAR_REPOSITORY"
export const REMOVE_STAR_REPOSITORY = "REMOVE_STAR_REPOSITORY"
export const GET_STARED_REPOSITORIES = "GET_STARED_REPOSITORIES"

export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS"
export const UPDATE_SETTINGS = "UPDATE_SETTINGS"
export const ERROR_UPDATE_SETTINGS = "ERROR_UPDATE_SETTINGS"
